-- MySQL Script generated by MySQL Workbench
-- Fri Feb  4 23:33:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `Nr_Rgm` INT(8) NOT NULL,
  `Nm_Nome` VARCHAR(40) NULL,
  `Nm_Pai` VARCHAR(40) NULL,
  `Nm_Mãe` VARCHAR(40) NULL,
  `Nt_Nascimento` DATE NULL,
  `Id_Sexo` CHAR(1) BINARY NULL,
  PRIMARY KEY (`Nr_Rgm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Classe` (
  `cd_Classe` INT(8) NOT NULL,
  `Nr_AnoLetivo` YEAR(4) NULL,
  `Nr_Serie` INT(2) NULL,
  `Sg_Turma` VARCHAR(45) NULL,
  `Cd_Escola` INT(6) NULL,
  `Cd_Grau` INT(2) NULL,
  `Cd_Periodo` INT(2) NULL,
  PRIMARY KEY (`cd_Classe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno_has_Classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno_has_Classe` (
  `Aluno_nr_Rgm` INT(8) NOT NULL,
  `Classe_cd_Classe` INT(8) NOT NULL,
  `dt_Matricula` DATE NULL,
  PRIMARY KEY (`Aluno_nr_Rgm`, `Classe_cd_Classe`),
  INDEX `fk_Aluno_has_Classe_Classe1_idx` (`Classe_cd_Classe` ASC) VISIBLE,
  INDEX `fk_Aluno_has_Classe_Aluno_idx` (`Aluno_nr_Rgm` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_has_Classe_Aluno`
    FOREIGN KEY (`Aluno_nr_Rgm`)
    REFERENCES `mydb`.`Aluno` (`Nr_Rgm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Classe_Classe1`
    FOREIGN KEY (`Classe_cd_Classe`)
    REFERENCES `mydb`.`Classe` (`cd_Classe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
